[package]
name = "adskalman"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.20"
num-traits = "0.2"
log = { version = "0.4", features = ["release_max_level_debug"] }
itertools = "0.8"
pretty-print-nalgebra = {git="https://github.com/strawlab/pretty-print-nalgebra", rev="d217d8f1412c72c19db24164f3d4030fa175559d"}
approx = "0.3"

[dev-dependencies]
nalgebra-rand-mvn = {git="https://github.com/strawlab/nalgebra-rand-mvn", rev="5bf9ffc17477622162c6655341c01fd47f3628c2"}
env_logger = "0.7"
