[package]
name = "adskalman-examples"
description = "Examples for the adskalman crate"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.29"
adskalman = {path=".."}
nalgebra-rand-mvn = {git="https://github.com/strawlab/nalgebra-rand-mvn", rev="33e05864184122adcde2b9989ff45f70a1e85098"}
env_logger = "0.9"
log = { version = "0.4", features = ["release_max_level_debug"] }
anyhow = "1.0"
